# Generated by Django 3.2.7 on 2021-10-01 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prymusNews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewOnNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(null=True, upload_to='uploaded-videos')),
                ('dated', models.DateTimeField(auto_now_add=True)),
                ('video_tags', models.CharField(max_length=200)),
                ('video_likes', models.IntegerField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prymusNews.news')),
            ],
        ),
    ]
