# Generated by Django 3.2.7 on 2021-10-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prymusNews', '0004_alter_viewonnews_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewonnews',
            name='video_likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
